version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "09:00"
    timezone: Asia/Singapore
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: eslint-plugin-react
    versions:
    - 7.23.0
  - dependency-name: husky
    versions:
    - 5.0.9
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
  - dependency-name: "@types/jest"
    versions:
    - 26.0.21
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.22.0
  - dependency-name: typescript
    versions:
    - 4.1.4
    - 4.2.2
  - dependency-name: ts-jest
    versions:
    - 26.5.2
  - dependency-name: "@types/react"
    versions:
    - 17.0.1
